import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  image: {
    width: 35,
    height: 35,
  },
  container: {
    padding: 10,
    flex: 1,
    justifyContent: 'center',
    paddingTop: 40,
  },
  grid: {
    flexDirection: 'column',
    alignItems: 'center',
    padding: 10,
  },
  row: {
    flexDirection: 'row',
  },
  cellWrapper: {
    margin: 0.3,
  },
  
  badge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'red',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 2,
    zIndex: 1,
  },
  
  buttonWrapper: {
    position: 'relative',
  },
  badgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  numberButtons: {
    flexDirection:'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    verticalAlign: 'middle',
  },
  numberText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  iconButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconDeleteButton:{
    alignSelf: 'center',
  },
  iconRestartButton: {
    alignSelf: 'baseline',
    transform: [{ rotate: '100deg' }],
  },
  allHintButtons: {
    top:-8,
    flexDirection: 'row',
  },
  hintWrapper: {
  flexDirection: 'row',
  alignItems: 'center',
  position: 'relative',
  },
  hintIconContainer: {
    zIndex: 2,
  },
  hintButtonsContainer: {
    flexDirection: 'column',
    right:0,
    marginLeft: 8,
    zIndex: 1,
  },

  hintText: {
    fontSize: 15,
    fontWeight: '600',
    marginTop: 20,
    color: 'white',
    paddingLeft: 10,
  },
  containerHint: {
    backgroundColor: 'rgb(0, 0, 0)',
    width: 110,
    height: 25,
    borderRadius: 8,
    position: 'absolute',
    top: 15,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -1,
  },
  containerHintLight: {
    backgroundColor: 'rgb(121, 122, 123)',
    width: 110,
    height: 30,
    borderRadius: 8,
    position: 'absolute',
    top: 15,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -2,
  },
  iconHintButton: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    marginLeft:10,
    right:10,
    margin:-5,
    position: 'relative',
  },
  imageHint: {
    width: 40,
    height: 40,
    transform: [{ rotate: '15deg' }],
  },
  imagePlus: {
    width: 40,
    height: 40,
    marginLeft: 4,
  },
  containerPlus: {
    backgroundColor: 'rgb(0, 0, 0)',
    width: 170,
    height: 25,
    borderRadius: 8,
    position: 'absolute',
    top: 15,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -1,
  },
  containerPlusLight: {
    backgroundColor: 'rgb(121, 122, 123)',
    width: 170,
    height: 30,
    borderRadius: 8,
    position: 'absolute',
    top: 15,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -2,
  },
  plusText: {
    fontSize: 15,
    fontWeight: '600',
    marginTop: 20,
    color: 'white',
    paddingLeft: 10,
  },
  iconPlusButton: {
    flexDirection: 'row',
    marginTop: 3,
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  diffText: {
    alignSelf: 'center',
    left: 55,
    marginTop: 10,
    fontSize: 20,
    fontWeight: '800',
  },

  containerDiff: {
    backgroundColor: 'rgb(0, 0, 0)',
    width: 130,
    height: 25,
    borderRadius: 8,
    position: 'absolute',
    top: 10,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -1,
  },
  containerDiffLight: {
    backgroundColor: 'rgb(121, 122, 123)',
    width: 130,
    height: 30,
    borderRadius: 8,
    position: 'absolute',
    top: 10,
    left: 0,
    right: 10,
    bottom: 0,
    zIndex: -2,
  },
  iconDiffButton: {
    position: 'absolute',
    top: 0,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },

  diffButtonText: {
    fontSize: 15,
    fontWeight: '600',
    marginTop: 20,
    color: 'white',
    paddingLeft: 10,
    bottom: 5,
  },
});

export default styles;
